import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ThemeProviderWrapper from "./providers/ThemeProvider";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} font-sans`}>
        <ThemeProviderWrapper>
          <Navbar />
          <main className="bg-zinc-200 dark:bg-zinc-900">{children}</main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
